### PR TITLE
Update default.conf.sample

### PR DESCRIPTION
**Pull request by JS-Media-Creation**
Makes GRAV's basic captcha work. 

See: https://github.com/getgrav/grav-plugin-form/issues/577#issuecomment-1257008933 

The issue has been closed, so I think it's the best workaround for now to make the basic captcha work.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-grav/blob/main/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

### CODE REVIEW

**Comment by Roxedus** [comment]
This is not a proper fix, would prefer if the offending regex match was found and removed/fixed/mitigated

**Comment by JS-Media-Creation** [comment]
@Roxedus Yes you're right, but in case that the issue has been already closed, my hope is rather low. And the basic captcha itself is a nice feature especially with regard to data protection, where I'm sad when you can't use it :(

**Comment by nemchik** [comment]
A potentially more proper fix is in https://github.com/linuxserver/docker-grav/pull/35

**Comment by JS-Media-Creation** [comment]
Solved by #35

**Pull request closed without merging**
